import Head from 'next/head'
import Image from 'next/image'
import styles from './Faq.module.css'
import { img } from 'react'

export default function Faq() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Aula 01 com Victor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>




      <main className={styles.main}>


        <div className={styles.boxRoadmap} >
          <div class="header">
            <div class="header-content">
              <div class="date">Phase 0<span>&nbsp;|&nbsp;Dez 2021</span></div>
              <div class="item-title" >The CreatorPRO MarketPLACE</div>
            </div>
            <img src="/icon-check.png" />
          </div>
          <p>Our own web 3.0 NFT marketplace for mint, sell and buy NFTs creator collections.</p>
                <p style={{ "color": "rgb(70, 197, 203)" }}></p>
        </div>

        <div className={styles.boxRoadmap} >
          <div class="header">
            <div class="header-content">
              <div class="date">Phase 1<span>&nbsp;|&nbsp;Dez 2021</span></div>
              <div class="item-title" >Ownership Managment</div>
            </div>
            <img src="/icon-check.png" />
          </div>
          <p>Our own web 3.0 NFT marketplace for mint, sell and buy NFTs creator collections.</p>
                <p style={{ "color": "rgb(70, 197, 203)" }}></p>
        </div>

        <div className={styles.boxRoadmap} >
          <div class="header">
            <div class="header-content">
              <div class="date">Phase 1<span>&nbsp;|&nbsp;Dez 2021</span></div>
              <div class="item-title" >Ownership Managment</div>
            </div>
            <img src="/icon-check.png" />
          </div>
          <p>Our own web 3.0 NFT marketplace for mint, sell and buy NFTs creator collections.</p>
                <p style={{ "color": "rgb(70, 197, 203)" }}></p>
        </div>

        <div className={styles.boxRoadmap} >
          <div class="header">
            <div class="header-content">
              <div class="date">Phase 1<span>&nbsp;|&nbsp;Dez 2021</span></div>
              <div class="item-title" >Ownership Managment</div>
            </div>
            <img src="/icon-check.png" />
          </div>
          <p>Our own web 3.0 NFT marketplace for mint, sell and buy NFTs creator collections.</p>
                <p style={{ "color": "rgb(70, 197, 203)" }}></p>
        </div>

        <div className={styles.boxRoadmap} >
          <div class="header">
            <div class="header-content">
              <div class="date">Phase 1<span>&nbsp;|&nbsp;Dez 2021</span></div>
              <div class="item-title" >Ownership Managment</div>
            </div>
            <img src="/icon-check.png" />
          </div>
          <p>Our own web 3.0 NFT marketplace for mint, sell and buy NFTs creator collections.</p>
                <p style={{ "color": "rgb(70, 197, 203)" }}></p>
        </div>

        <div className={styles.boxRoadmap} >
          <div class="header">
            <div class="header-content">
              <div class="date">Phase 1<span>&nbsp;|&nbsp;Dez 2021</span></div>
              <div class="item-title" >Ownership Managment</div>
            </div>
            <img src="/icon-check.png" />
          </div>
          <p>Our own web 3.0 NFT marketplace for mint, sell and buy NFTs creator collections.</p>
                <p style={{ "color": "rgb(70, 197, 203)" }}></p>
        </div>

        <div className={styles.boxRoadmap} >
          <div class="header">
            <div class="header-content">
              <div class="date">Phase 1<span>&nbsp;|&nbsp;Dez 2021</span></div>
              <div class="item-title" >Ownership Managment</div>
            </div>
            <img src="/icon-check.png" />
          </div>
          <p>Our own web 3.0 NFT marketplace for mint, sell and buy NFTs creator collections.</p>
                <p style={{ "color": "rgb(70, 197, 203)" }}></p>
        </div>

        <div className={styles.boxRoadmap} >
          <div class="header">
            <div class="header-content">
              <div class="date">Phase 1<span>&nbsp;|&nbsp;Dez 2021</span></div>
              <div class="item-title" >Ownership Managment</div>
            </div>
            <img src="/icon-check.png" />
          </div>
          <p>Our own web 3.0 NFT marketplace for mint, sell and buy NFTs creator collections.</p>
                <p style={{ "color": "rgb(70, 197, 203)" }}></p>
        </div>

        <div className={styles.boxRoadmap} >
          <div class="header">
            <div class="header-content">
              <div class="date">Phase 1<span>&nbsp;|&nbsp;Dez 2021</span></div>
              <div class="item-title" >Ownership Managment</div>
            </div>
            <img src="/icon-check.png" />
          </div>
          <p>Our own web 3.0 NFT marketplace for mint, sell and buy NFTs creator collections.</p>
                <p style={{ "color": "rgb(70, 197, 203)" }}></p>
        </div>

        <div className={styles.boxRoadmap} >
          <div class="header">
            <div class="header-content">
              <div class="date">Phase 1<span>&nbsp;|&nbsp;Dez 2021</span></div>
              <div class="item-title" >Ownership Managment</div>
            </div>
            <img src="/icon-check.png" />
          </div>
          <p>Our own web 3.0 NFT marketplace for mint, sell and buy NFTs creator collections.</p>
                <p style={{ "color": "rgb(70, 197, 203)" }}></p>
        </div>

        <div className={styles.boxRoadmap} >
          <div class="header">
            <div class="header-content">
              <div class="date">Phase 1<span>&nbsp;|&nbsp;Dez 2021</span></div>
              <div class="item-title" >Ownership Managment</div>
            </div>
            <img src="/icon-check.png" />
          </div>
          <p>Our own web 3.0 NFT marketplace for mint, sell and buy NFTs creator collections.</p>
                <p style={{ "color": "rgb(70, 197, 203)" }}></p>
        </div>

        <div className={styles.boxRoadmap} >
          <div class="header">
            <div class="header-content">
              <div class="date">Phase 1<span>&nbsp;|&nbsp;Dez 2021</span></div>
              <div class="item-title" >Ownership Managment</div>
            </div>
            <img src="/icon-check.png" />
          </div>
          <p>Our own web 3.0 NFT marketplace for mint, sell and buy NFTs creator collections.</p>
                <p style={{ "color": "rgb(70, 197, 203)" }}></p>
        </div>

        <div className={styles.boxRoadmap} >
          <div class="header">
            <div class="header-content">
              <div class="date">Phase 1<span>&nbsp;|&nbsp;Dez 2021</span></div>
              <div class="item-title" >Ownership Managment</div>
            </div>
            <img src="/icon-check.png" />
          </div>
          <p>Our own web 3.0 NFT marketplace for mint, sell and buy NFTs creator collections.</p>
                <p style={{ "color": "rgb(70, 197, 203)" }}></p>
        </div>

        <div className={styles.boxRoadmap} >
          <div class="header">
            <div class="header-content">
              <div class="date">Phase 1<span>&nbsp;|&nbsp;Dez 2021</span></div>
              <div class="item-title" >Ownership Managment</div>
            </div>
            <img src="/icon-check.png" />
          </div>
          <p>Our own web 3.0 NFT marketplace for mint, sell and buy NFTs creator collections.</p>
                <p style={{ "color": "rgb(70, 197, 203)" }}></p>
        </div>


        <div className={styles.boxRoadmap}>
          <div class="header">
            <div class="header-content">
              <div class="date">Phase 1<span>&nbsp;|&nbsp;Dez 2021</span></div>
              <div class="item-title" >Ownership Managment</div>
            </div>
            <img src="/icon-close.png" />
          </div>
          <p>Agreements for ownership managment and revenue share with distributors in more then 70+ dsps .</p>
          <p >
          </p>
        </div>


      </main>


      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
